<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNbp6zoy\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNbp6zoy/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerNbp6zoy.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerNbp6zoy\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerNbp6zoy\appProdProjectContainer([
    'container.build_hash' => 'Nbp6zoy',
    'container.build_id' => '97c38a91',
    'container.build_time' => 1640268420,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNbp6zoy');
