<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTj44a6t\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTj44a6t/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerTj44a6t.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerTj44a6t\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerTj44a6t\appProdProjectContainer([
    'container.build_hash' => 'Tj44a6t',
    'container.build_id' => '8e678812',
    'container.build_time' => 1640268548,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTj44a6t');
